### ISSUE TITLE
plugin processes: mismatch between implementation and pillar.example

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/collectd-formula#132]
To configure plugin processes, pillar.example give this example
```
collectd:
  plugins:
    processes:
      - java
      - python
```

But it does not work like this. When reading `collectd/files/processes.conf` we see it expects keys `Processes` and `ProcessesMatch`.

Event if I don't like this syntax (key names with Capital) and it's not homogenous (most plugins use pillar data with key names in lowercase), it seems that this syntax exists since 2015, so we just need to make pillar.example correct.
