### ISSUE TITLE
collectd.java fails with default values

### ISSUE THREAD

**Issue by babilen** [saltstack-formulas/collectd-formula#26]
Trying to use `collectd.java` on Debian results in the following error:

```
----------
          ID: /usr/lib/collectd/java.so
    Function: file.symlink
      Result: False
     Comment: File exists where the symlink /usr/lib/collectd/java.so should be
     Started: 10:12:11.219063
    Duration: 0.721 ms
     Changes: 
```

It would be muich appreciated if this insanity could be fixed in such a way that the formula works with the default settings.
